### ISSUE TITLE
Update "Getting Started" with oc cluster up docs

### ISSUE THREAD

**Issue by pmacko1** [aerogear/mobile-core#109]
## Description
https://github.com/aerogear/mobile-core/blob/master/docs/walkthroughs/getting-started-installation.adoc
## Update with
https://github.com/aerogear/mobile-docs/blob/master/modules/ROOT/pages/installing-mobile-services.adoc

**Comment by johnfriz** [comment]
@pmacko1 - The getting started guide has been updated significantly since this issue was raised and I believe the new structure addresses this issue. Can you take a look at https://docs.aerogear.org/aerogear/latest/getting-started.html and see if has actually addressed this issue.

**Comment by pmacko1** [comment]
@johnfriz this issue is about docs in this repo, not mobile-docs.

What are we planning to do with docs living besides code?

**Comment by johnfriz** [comment]
@pmacko1 - We will be moving any user facing docs to the mobile-docs repo (which will be most of the existing content). Anything that remains will be contributor focused.

@finp - FYI... still need to finalise the list of content that is moving to mobile-docs. Can you clear out the ones we have already moved over?

**Comment by wei-lee** [comment]
@pmacko1,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
