### ISSUE TITLE
installer error for oc tools on fedora

### ISSUE THREAD

**Issue by finp** [aerogear/mobile-core#110]
fedora 27: 

TASK [openshift-origin-client-tools : unarchive] ************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/tmp/openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz\". Make sure the required command to extract the file is installed. Command \"/bin/gtar\" could not handle archive. Command \"/bin/unzip\" could not handle archive."}

**Comment by johnfriz** [comment]
@finp are you still seeing this issue? If so, are there any more details you can provide?

**Comment by camilamacedo86** [comment]
@finp could you check if it will be solved with the PR https://github.com/aerogear/mobile-core/pull/193 ?

**Comment by finp** [comment]
unable to replicate, even without #193, closing

**Comment by camilamacedo86** [comment]
Hi @finp,

Thank you for verify.  Could you approve the PR, please?
