### ISSUE TITLE
Provide instructions for installing mobile services on an existing OpenShift cluster

### ISSUE THREAD

**Issue by dneary** [aerogear/mobile-core#127]
## Description

I already have a multi-node OpenShift cluster running, and have a username and password to connect to it. I have shell access to the OpenShift master node, if I need it.

I would like instructions for installing Aerogear mobile services to my OpenShift - I don't really know a lot about OpenShift, but the "Getting started" guide talks about oc cluster up only, and when I run the installer.sh script, I get the error that Docker is not running. 

## Environment

*Operating system*: Linux (Fedora) on laptop, Linux (CentOS 7.x) running on OpenShift nodes
*OpenShift versions*:

OpenShift Master:
    v3.9.0+ba7faec-1 
Kubernetes Master:
    v1.9.1+a0ce1bc657 
OpenShift Web Console:
    v3.9.0+b600d46-dirty 

## Steps to reproduce

Attempt to follow the getting started guide with an existing multi-user OpenShift Origin. Running "installer/installer.sh" should give the error that Docker is not running.

**Comment by maleck13** [comment]
@dneary Thanks for the issue. The installer here is meant for local dev using oc cluster up. We are working on allowing it to be installed on any 3.9 => cluster . Util then please take a look at the following doc and see does it suit your needs

https://github.com/aerogear/mobile-core/blob/master/docs/walkthroughs/setup-mobile-on-existing-cluster.adoc

**Comment by johnfriz** [comment]
@dneary - There is an Open PR here for automating the installation on an existing cluster: https://github.com/aerogear/mobile-core/pull/125

If you had a few minutes to give it a go and provide feedback,. that would be great :-D

**Comment by dneary** [comment]
I have had some issues with the .yml file - can't figure out how to apply the playbook to a cluster which is running somewhere other than localhost. I am not an Ansible expert by any means!

I would have expected an "oc new-app" or "oc apply" to connect to a running OpenShift with the OpenShift client..

**Comment by maleck13** [comment]
I believe you may need to run this script on the host currently ping @wei-lee.

**Comment by wei-lee** [comment]
@dneary You can run the script on localhost, you just need to make sure oc is connected to the remote cluster.

**Comment by wei-lee** [comment]
Hi @dneary,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
