### ISSUE TITLE
Unable to install with Ansible version 2.4 or above <2.6 as defined in the doc

### ISSUE THREAD

**Issue by camilamacedo86** [aerogear/mobile-core#130]
## Description
**WHAT:** Unable to install with Ansible version 2.4 or above <2.6
**WHERE:** iOS env
**WHEN:** Run the command `./installer/install.sh` and is following the pre-requirements in the docs[1]

[1] - https://docs.aerogear.org/aerogear/latest/getting-started.html#procedure

## Environment

*Operating system*: iOS
*OpenShift versions*: 

## Steps to reproduce

* When the version 2.4 is installed:

```
cmacedo@camilas-MBP ~/mobile-core ((HEAD detached at 1.0.0)) $ ansible --version
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/Users/cmacedo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

Then after cloning the project, and checkout tag 1.0.0. Following the output when the command `./installer/install.sh` is executed.

```
cmacedo@camilas-MBP ~/mobile-core ((HEAD detached at 1.0.0)) $ ./installer/install.sh

Checking Docker exists
✓ Docker check passed.
Checking Docker is running
✓ Docker check passed.
Checking Docker version. Should be using Stable channel
✓ Docker check passed.

Checking Python exists
✓ Python check passed.
Checking Python version. Should be >= 2.7
✓ Python check passed.

Checking Ansible exists
✓ Ansible check passed.
Checking Ansible version. Should be >= 2.6
Ansible version is < 2.6. Install ansible>=2.6 using pip install ansible>=2.6
cmacedo@camilas-MBP ~/mobile-core ((HEAD detached at 1.0.0)) $ 
```

PS.: It is possible to be solved by updating the [prerequisites](https://docs.aerogear.org/aerogear/latest/getting-started.html#prerequisites) in the documentation of the project.

**Comment by matskiv** [comment]
@camilamacedo86 I think this is now resolved by my docs update: https://github.com/aerogear/mobile-docs/pull/227

**Comment by camilamacedo86** [comment]
Closing since it is solved in the docs.
