### ISSUE TITLE
Info message to install Ansible is confusing and not accurate when is required a updated

### ISSUE THREAD

**Issue by camilamacedo86** [aerogear/mobile-core#131]
## Description
**WHAT**: Message "Ansible version is < 2.6. Install ansible>=2.6 using pip install ansible>=2.6" is shown
**WHERE**: iOS
**WHEN**: run the install command `./installer/install.sh`
**IMPACT**: 
* Not clear what command need to be executed. Is it  `pip install ansible>=2.6` or `pip install ansible`?
* The command `pip install ansible` will NOT update the current installation 

#### What is expected?
* A clear message with the command that should be executed. ( It can be solved by improving the text as for example: `Ansible installed version is < 2.6. To fix it install an ansible version >=2.6 by "$<command>"`
* Inform the correct command to update the current installation when it already exists. `pip install ansible` will NOT update the current installation and it should appears when the ansible is not installed in the env ONLY. If the problem is version > of min requirements then it should shows the command to updated the current version to the min required version.
* The command to update the current version to the latest pusblish is `pip install ansible --upgrade --user`

## Environment

*Operating system*: iOS
*OpenShift versions*: 

## Steps to reproduce
Follow up the steps to install in the [doc](https://docs.aerogear.org/aerogear/latest/getting-started.html#procedure)

**Comment by maleck13** [comment]
Thanks for the issue @camilamacedo86  did running pip install --upgrade ansible solve the issue for you? If so a PR to change the message would be welcome

**Comment by camilamacedo86** [comment]
Hi @maleck13,
The correct command was added in the issue description as the expected behaviour and it worked for me. 

"The command to update the current version to the latest publish is pip install ansible --upgrade --user" 

PS.: --user option is important to don't face the pip permission error. See [here](https://github.com/fonttools/fonttools/issues/796)

**Comment by camilamacedo86** [comment]
PR made https://github.com/aerogear/mobile-core/pull/175

**Comment by camilamacedo86** [comment]
Solve in the PR/merged
