### ISSUE TITLE
Unclear how to get better debug info from installer script

### ISSUE THREAD

**Issue by damienomurchu** [aerogear/mobile-core#133]
## Description

Its not clear how to get better debug info from the installer script. You can modify the installer script [here](https://github.com/aerogear/mobile-core/blob/master/installer/install.sh#L221) and [here](https://github.com/aerogear/mobile-core/blob/master/installer/install.sh#L229) to pass in `-v`/ `-vv` flags here if you know ansible, but its unclear how to do this by just running the bash script

## Environment

*Operating system*: Fedora 26
*OpenShift versions*: 3.9

## Steps to reproduce

- run the installer script, hit an issue, and scream at lack of debuggable console output

**Comment by wei-lee** [comment]
@damienomurchu,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
