### ISSUE TITLE
confusing DockerHub Username default in installer

### ISSUE THREAD

**Issue by mmurphy** [aerogear/mobile-core#134]
## Description
installer says
> DockerHub Username (Defaults to DOCKERHUB_USERNAME env var)

I don't think this is clear.  If it's going to use the current value of DOCKERHUB_USERNAME, then I think it should show what that value is.  If it's going to use, whatever the future values of DOCKERHUB_USERNAME, then I think it has to be more explicit about this.

## Environment

*MacOS*:
*OpenShift 3.9*: 

## Steps to reproduce
./installer/install.sh

**Comment by camilamacedo86** [comment]
PR made to solve it : https://github.com/aerogear/mobile-core/pull/183

**Comment by camilamacedo86** [comment]
It was solved,
