### ISSUE TITLE
Wrong message if python is not installed

### ISSUE THREAD

**Issue by matskiv** [aerogear/mobile-core#137]
## Description
When python is not installed it shows this message as a suggestion how to install it: "pip install ansible>=2.3"

Code:
https://github.com/aerogear/mobile-core/blob/master/installer/install.sh#L91

I didn't experience this problem because I already had python installed, I just noticed this message in source code - that's why I didn't fill Environment and  Steps to reproduce.

**Comment by camilamacedo86** [comment]
Done a PR https://github.com/aerogear/mobile-core/pull/174

**Comment by camilamacedo86** [comment]
Solved in the PR
