### ISSUE TITLE
Installer script fails on docker out of space error when using docker v18.0.3

### ISSUE THREAD

**Issue by damienomurchu** [aerogear/mobile-core#138]
## Description

Install fails on [this step](https://github.com/aerogear/mobile-core/blob/master/installer/roles/patch-origin-web-console/tasks/main.yml#L19) with a docker out of space issue. Abundant space on local machine, and seems this is error is related to space on the openshift origin container. 

Running script with `-vvv` flag for ansible-playbook command, and also checking docker daemon logs points to an out of space error. Sufficient space on local machine as mentioned (& confirmed with `df -h` and `df -i`).

After script fails, oc cluster is inaccessible, and accessing the web console errors out with a 502. 

No longer have docker 18.0.3 installed (rolled back to docker version 17.12.0, which runs ok with installer script, no errors). Will try add further info in a gist when I re-install 18.0.3 to replicate issue again.

## Environment

*Operating system*: Fedora 26
*OpenShift versions*: 3.9
*Docker version*: 18.0.3 

## Steps to reproduce

- Run installer.sh script, and watch it fail at above stage

**Comment by camilamacedo86** [comment]
Hi @damienomurchu,

Just to share.  I could not reproduce this issue in the Mac OS X with the following docker version. 

```
cmacedo@camilas-MBP ~/mobile-core (LAYOUT) $ docker version
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:06:22 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:14:32 2018
  OS/Arch:	linux/amd64
  Experimental:	true
cmacedo@camilas-MBP ~/mob

```

**Comment by damienomurchu** [comment]
@camilamacedo86 Good to know this issue is not present with 18.03 on a different OS. As per [OpenShift documentation](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#prerequisites) only v1.13 of docker is supported for OpenShift 3.9

**Comment by camilamacedo86** [comment]
Hi @damienomurchu,

It the doc is "This command was released with the 1.3+ version of oc client tools, so you must be using version 1.3+ or newer for this command to work", which means that the min required version is `1.3`, but not that only this version is supported. 

Is make sense to you the previous explanation about the issue described here and that it is more related to the docker and its setup/configuration? Could you check the link added? Are you ok in close this one or do you not agree with it?

**Comment by damienomurchu** [comment]
@camilamacedo86 `This command was released with the 1.3+ version of oc client tools, so you must be using version 1.3+ or newer for this command to work` - this just means `oc cluster up` & `oc cluster down` are available form 1.3 onwards. The only version of docker officially supported with OC 3.9 is docker v1.13 as per [link](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#prerequisites)

**Comment by camilamacedo86** [comment]
@damienomurchu could you check the following.. 

"if you search for this kind of issue, see [here](https://stackoverflow.com/questions/42703481/why-has-docker-volume-run-out-of-space) for example, shows something more related to the install/setup of the current docker than an issue in a specific version. Probably, if you just re-install the version used when the issue was faced and/or try fixed as described in this link instead of installing another version it could be solved too. "

**Comment by damienomurchu** [comment]
Closing this issue, as per previous comment, oc versions > 1.13 are not officially supported by OpenShift yet.
