### ISSUE TITLE
Typo: Mobile builds are not "avaialble" for Xamarin.

### ISSUE THREAD

**Issue by grdryn** [aerogear/mobile-core#139]
## Description
![image](https://user-images.githubusercontent.com/442386/42625913-e3578834-85c0-11e8-9ab6-b84dfeaa3917.png)

## Steps to reproduce
1. Try to create a Build for a Xamarin app, see the typo in the message.

**Comment by jasonmadigan** [comment]
typo: https://github.com/aerogear/origin-web-console/blob/aerogear-mcp/app/views/browse/mobile-clients.html#L117

**Comment by grdryn** [comment]
https://github.com/aerogear/origin-web-console/pull/93

**Comment by grdryn** [comment]
Closed via https://github.com/aerogear/origin-web-console/pull/93
