### ISSUE TITLE
Can't create Xamarin apps through "Mobile CI/CD" service in OpenShift

### ISSUE THREAD

**Issue by grdryn** [aerogear/mobile-core#141]
## Description
I followed the getting started guide, and foolishly chose Xamarin. I thought that since I'm using Linux on my developer machine that I'd just be able to build the app using the "Mobile CI/CD" service, but when I click on "Builds" for the mobile client, I get a [carelessly worded message](https://github.com/aerogear/mobile-core/issues/139) that it's not possible.

## Environment
OpenShift

*OpenShift versions*: 
```
OpenShift Master: v3.9.0+b8265d6-31 
Kubernetes Master: v1.9.1+a0ce1bc657 
OpenShift Web Console: v3.11.0-alpha.0+719cfb3-dirty 
```

## Steps to reproduce
Try to create a build for a Xamarin app.

**Comment by wei-lee** [comment]
Hi @grdryn,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
