### ISSUE TITLE
Unable to know what each item/template means

### ISSUE THREAD

**Issue by camilamacedo86** [aerogear/mobile-core#143]
## Description
**WHAT** Unable to know what each item/template means
**WHERE** Mobile Catalog >> All
**WHEN** the user see the item doesn't know what it is, and what does and how it cab useful

#### Suggestion:
Each item could have an info button with a small info and with the link for the README of the project

## Environment

*Operating system*: iOS
*OpenShift versions*: Origin 3.9

## Steps to reproduce
Go to  Mobile Catalog >> All and check sync for example. What does it mean? It is not intuitive at all. 

<img width="942" alt="screen shot 2018-07-12 at 11 09 57" src="https://user-images.githubusercontent.com/7708031/42627175-2794331e-85c4-11e8-94f2-2e25a7743127.png">

**Comment by wei-lee** [comment]
Hi @camilamacedo86,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
