### ISSUE TITLE
Parameters for services are not intuitive

### ISSUE THREAD

**Issue by camilamacedo86** [aerogear/mobile-core#144]
## Description
**WHAT:** Unable to know what means Mobile Client ID
**WHERE:** Mobile Catalog Services
**WHEN** the option `Create a secret in My Project to be used later` is selected

<img width="877" alt="screen shot 2018-07-12 at 11 17 04" src="https://user-images.githubusercontent.com/7708031/42627508-26b0b8c2-85c5-11e8-900c-c78df22473e9.png">

<img width="881" alt="screen shot 2018-07-12 at 11 17 10" src="https://user-images.githubusercontent.com/7708031/42627516-2a8dad2e-85c5-11e8-8212-b0587a1d1e1b.png">

PS.: Could the text input be a drop down? 

## Environment

*Operating system*: iOS
*OpenShift versions*: 3.9

## Steps to reproduce
1. Go to Catalog >> Mobile >> Services
2. Select a Service
3. In the Biding step select `Create a secret in My Project to be used later`

**Comment by wei-lee** [comment]
Hi @camilamacedo86,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
