### ISSUE TITLE
Label duplicated in the popup to create the items

### ISSUE THREAD

**Issue by camilamacedo86** [aerogear/mobile-core#145]
## Description

**WHAT** Label duplicated
**WHERE** Catalog >> Mobile >> Each item >> 
**WHEN**: try to create a new item

<img width="345" alt="screen shot 2018-07-12 at 11 23 31" src="https://user-images.githubusercontent.com/7708031/42627817-08d36ed4-85c6-11e8-8298-611724d3ee6c.png">
<img width="330" alt="screen shot 2018-07-12 at 11 21 28" src="https://user-images.githubusercontent.com/7708031/42627818-08f5748e-85c6-11e8-966f-f16b905f2ea9.png">

## Environment

*Operating system*: iOS
*OpenShift versions*: 3.9

## Steps to reproduce
 Catalog >> Mobile >> Select an Item

**Comment by wei-lee** [comment]
Hi @camilamacedo86,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
