### ISSUE TITLE
Field BundleID in iOS App is missing explanation

### ISSUE THREAD

**Issue by camilamacedo86** [aerogear/mobile-core#146]
## Description
**WHAT** Field BundleID in OS App is missing description/info
**WHERE** Catalog >> Mobile >> App or All >> iOS
**WHEN** A new IOS app is created 
**IMPACT** User did not know what bundle means, and where and how it will be used, as what should be added at this point. 

<img width="869" alt="screen shot 2018-07-12 at 11 25 10" src="https://user-images.githubusercontent.com/7708031/42628019-b398d7e6-85c6-11e8-9934-3267d12898e4.png">

## Environment

*Operating system*: iOS
*OpenShift versions*: Origin 3.9

## Steps to reproduce
1. Go to Catalog >> Mobile >> App or All >> 
2. Click on iOS >> Next

**Comment by wei-lee** [comment]
Hi @camilamacedo86,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
