### ISSUE TITLE
Obligatory fields are missing alerts

### ISSUE THREAD

**Issue by camilamacedo86** [aerogear/mobile-core#147]
## Description
**WHAT**: Obligatory fields are missing alerts
**WHERE**: Catalog >> Mobile >> App >> Xamarin >> Configuration 
**WHEN**: when try to create a app of this kind

Following the image. Note that because of it is missing the info in the "Package Name" is not possible click on create. An alert as it has in other places should appear to make clear that it is not possible to move forward without this info. 

<img width="877" alt="screen shot 2018-07-12 at 11 31 36" src="https://user-images.githubusercontent.com/7708031/42628217-51fc3d9c-85c7-11e8-8a37-cfedcdc2404d.png">

It happens in many places. Wizards. 

## Environment

*Operating system*: iOS
*OpenShift versions*: Origin 3.9

## Steps to reproduce
1. Catalog >> Mobile >> App >> Xamarin >>
2. Click on Next and go to the cinfiguration step

**Comment by wei-lee** [comment]
Hi @camilamacedo86,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
