### ISSUE TITLE
Package Name did not have validation and allow special characters and spaces

### ISSUE THREAD

**Issue by camilamacedo86** [aerogear/mobile-core#149]
## Description
**WHAT**: Package Name did not have validation and allow special characters and spaces
**WHERE**: Catalog >> Mobile >> App >> Xamarin >> Configuration 
**WHEN**: when try to create a app of this kind

Following the image. Is a possible exist a package name with special characters? Could it not cause issues? 

<img width="647" alt="screen shot 2018-07-12 at 11 39 00" src="https://user-images.githubusercontent.com/7708031/42628585-7657ee7e-85c8-11e8-90fd-24a51124fc95.png">

## Environment

*Operating system*: iOS
*OpenShift versions*: Origin 3.9

## Steps to reproduce
1. Catalog >> Mobile >> App >> Xamarin >>
2. Click on Next and go to the cinfiguration step

**Comment by wei-lee** [comment]
Hi @camilamacedo86,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
