### ISSUE TITLE
Project Name field did not have validation and allow special characters and spaces

### ISSUE THREAD

**Issue by camilamacedo86** [aerogear/mobile-core#150]
## Description
**WHAT**: Project Name field did not have validation and allow special characters and spaces
**WHERE**: Catalog >> Mobile >> 
**WHEN**: when trying to create an item

<img width="891" alt="screen shot 2018-07-12 at 11 42 39" src="https://user-images.githubusercontent.com/7708031/42628779-0eaaed84-85c9-11e8-9814-a6ff3751803b.png">

## Environment

*Operating system*: iOS
*OpenShift versions*: Origin 3.9

## Steps to reproduce
1. Catalog >> Mobile 
2. Create an item

**Comment by wei-lee** [comment]
Hi @camilamacedo86,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
