### ISSUE TITLE
Android build of showcase app fails (but still runs in emulator)

### ISSUE THREAD

**Issue by damienomurchu** [aerogear/mobile-core#151]
## Description

Android build of [showcase app](git clone https://github.com/aerogear/android-showcase-template.git) fails when built in Android studio with `./gradlew clean build` (App still seems to run fine though, strangely enough..).

```
11:35:34.346 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
11:35:34.346 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:35:34.346 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
11:35:34.346 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Some problems were found with the configuration of task ':app:packageRelease'.
11:35:34.346 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > No value has been specified for property 'signingConfig.keyPassword'.
11:35:34.346 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > No value has been specified for property 'signingConfig.storePassword'.
11:35:34.346 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:35:34.346 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
11:35:34.346 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
11:35:34.346 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:35:34.347 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
11:35:34.347 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
11:35:34.347 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 30s
```

## Environment

*Operating system*: Fedora 26
*OpenShift versions*: 3.9
*Android Studio version*: 3.0.1

## Steps to reproduce

- clone android studio showcase app above
- open in android studio
- open terminal in android studio & run `./gradlew clean build`

**Comment by wtrocki** [comment]
@damienomurchu this command is used to build for production which requires certificate. Error means that apk was not signed so it will work on emulator. If the command was from the documentation then this is documentation issue (we should use debug build)

**Comment by wei-lee** [comment]
Hi @damienomurchu,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
