### ISSUE TITLE
Android SDK License Agreement field is missing the license that is mandatory agree 

### ISSUE THREAD

**Issue by camilamacedo86** [aerogear/mobile-core#153]
## Description
**WHAT:** Android SDK License Agreement is a text box when it should be a checked box
**WHERE** Catalog >> Mobile >> Services >> Mobile CI|CD 
**WHEN**: trying to create it. 
**IMPACT** How the user can be obligated to agree with a license without being able to read it? Is this field really required? Note that the info for a link that is not clickable just appears after write yes. 
 
<img width="872" alt="screen shot 2018-07-12 at 11 49 12" src="https://user-images.githubusercontent.com/7708031/42628952-9f51a8f0-85c9-11e8-9efc-459e8a6fb4e3.png">

<img width="724" alt="screen shot 2018-07-12 at 11 54 45" src="https://user-images.githubusercontent.com/7708031/42629190-7b926368-85ca-11e8-8d9a-6a838928c1ec.png">

## Environment

*Operating system*: iOS
*OpenShift versions*: 3.9

## Steps to reproduce
1. Go to Catalog >> Mobile >> Services >> 
2. Create a new Mobile CI|CD

**Comment by wei-lee** [comment]
Hi @camilamacedo86,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
