### ISSUE TITLE
Mobile App Creation Wizard - Add explanations of fields on mobile app creation wizard

### ISSUE THREAD

**Issue by davidffrench** [aerogear/mobile-core#154]
## Description
Add explanations of fields on mobile app creation wizard. E.g. a hover over question mark (?) to explain what is needed in the field.

## Steps to reproduce
1. Navigate to your OpenShift service catalog
2. Select iOS App and click next
3. It would be useful to give an explanation on all fields during these wizards.

![2018-07-12_11-53-07](https://user-images.githubusercontent.com/1596014/42629159-5ef40aa4-85ca-11e8-8fef-4d84d387a450.png)

**Comment by camilamacedo86** [comment]
In the customer/user point of view, it is a bug because they cannot understand and know what should be imputed.

**Comment by wei-lee** [comment]
Hi @davidffrench,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
