### ISSUE TITLE
Mobile App Creation Wizard - Duplicate text on the first screen

### ISSUE THREAD

**Issue by davidffrench** [aerogear/mobile-core#155]
## Description
The first screen of the mobile app creation wizard displays the same line of text twice. 
Sets up an <app type> App representation.

## Environment

*Operating system*: MacOS
*OpenShift versions*: 3.9

## Steps to reproduce
1. Navigate to your OpenShift service catalog
2. Select iOS App
![2018-07-12_12-00-08](https://user-images.githubusercontent.com/1596014/42629430-2d036ae8-85cb-11e8-896f-f8858c69e496.png)

**Comment by camilamacedo86** [comment]
The same of : https://github.com/aerogear/mobile-core/issues/145 ( duplicated )

**Comment by wei-lee** [comment]
Hi @davidffrench,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
