### ISSUE TITLE
Unable to add name to the services

### ISSUE THREAD

**Issue by camilamacedo86** [aerogear/mobile-core#157]
## Description

The user/customer can create more than one service of each kind with a different setup and then is not possible to identify each one. 

<img width="751" alt="screen shot 2018-07-12 at 12 16 38" src="https://user-images.githubusercontent.com/7708031/42630140-a2c50334-85cd-11e8-85d3-a718e23fb25c.png">

## Environment

*Operating system*: iOS
*OpenShift versions*: 3.9

## Steps to reproduce

Create more than once service with the same type.

**Comment by wei-lee** [comment]
Hi @camilamacedo86,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
