### ISSUE TITLE
Why are the mobile apps showing up as provisioned services?

### ISSUE THREAD

**Issue by davidffrench** [aerogear/mobile-core#158]
## Description
In my opinion, it is confusing to have the created mobile apps showing up as provisioned services. IS there a purpose to have these shown to the user and not hidden?

## Environment

*Operating system*: MacOS 10.13.5
*OpenShift versions*: 3.9

## Steps to reproduce
1. Create a mobile app from the service catalog
2. Navigate to your project
![2018-07-12_12-22-44](https://user-images.githubusercontent.com/1596014/42630358-59bf6fac-85ce-11e8-8b21-1388dc3f5682.png)

**Comment by wei-lee** [comment]
Hi @davidffrench,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
