### ISSUE TITLE
DataSync provisioning fails.

### ISSUE THREAD

**Issue by camilamacedo86** [aerogear/mobile-core#159]
## Description

Following the error faced.

`The service failed. Error provisioning ServiceInstance of ClusterServiceClass (K8S: "e54801e9be6229e2d924f7bc349ad20f" ExternalName: "dh-data-sync-apb") at ClusterServiceBroker "ansible-service-broker": Status: 400; ErrorMessage: <nil>; Description: not found; ResponseError: <nil>
`

Following the place.

<img width="1164" alt="screen shot 2018-07-12 at 12 28 28" src="https://user-images.githubusercontent.com/7708031/42630573-207e5216-85cf-11e8-9990-d08454a7a7f5.png">

Also, where this service? Not able to find in the project via the command line to get the logs. 

```
cmacedo@camilas-MBP ~/mobile-core ((HEAD detached at 1.0.0)) $ oc project myproject
Now using project "myproject" on server "https://192.168.1.9:8443".
cmacedo@camilas-MBP ~/mobile-core ((HEAD detached at 1.0.0)) $ oc get all
NAME              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/keycloak   1         1         1            1           58m
deploy/postgres   1         1         1            1           58m

NAME                     DESIRED   CURRENT   READY     AGE
rs/keycloak-86f589887d   1         1         1         58m
rs/postgres-79c9f59d7b   1         1         1         58m

NAME                                   REVISION   DESIRED   CURRENT   TRIGGERED BY
deploymentconfigs/data-sync-server     1          1         1         config
deploymentconfigs/data-sync-ui         1          1         1         config
deploymentconfigs/postgres-data-sync   1          1         1         config

NAME                      HOST/PORT                                       PATH      SERVICES           PORT      TERMINATION     WILDCARD
routes/data-sync-server   data-sync-server-myproject.192.168.1.9.nip.io             data-sync-server   web       edge/Redirect   None
routes/data-sync-ui       data-sync-ui-myproject.192.168.1.9.nip.io                 data-sync-ui       web       edge/Redirect   None
routes/keycloak           keycloak-myproject.192.168.1.9.nip.io                     keycloak           web       edge/Redirect   None

NAME                            READY     STATUS    RESTARTS   AGE
po/data-sync-server-1-dghdp     1/1       Running   0          1h
po/data-sync-ui-1-mnbzl         2/2       Running   0          1h
po/keycloak-86f589887d-9pr8n    1/1       Running   0          58m
po/postgres-79c9f59d7b-z8xll    1/1       Running   0          58m
po/postgres-data-sync-1-zs47s   1/1       Running   0          1h

NAME                      DESIRED   CURRENT   READY     AGE
rc/data-sync-server-1     1         1         1         1h
rc/data-sync-ui-1         1         1         1         1h
rc/postgres-data-sync-1   1         1         1         1h

NAME                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
svc/data-sync-server     ClusterIP   172.30.97.123    <none>        443/TCP    1h
svc/data-sync-ui         ClusterIP   172.30.64.48     <none>        443/TCP    1h
svc/keycloak             ClusterIP   172.30.198.248   <none>        80/TCP     58m
svc/postgres             ClusterIP   172.30.143.35    <none>        5432/TCP   59m
svc/postgres-data-sync   ClusterIP   172.30.225.233   <none>        5432/TCP   1h
cmacedo@camilas-MBP ~/mobile-core ((HEAD detached at 1.0.0)) $ 

````

## Environment

*Operating system*: iOS
*OpenShift versions*: 3.9

## Steps to reproduce
1. Go to Catalog >> Mobile >> Services >> 
2. Create Sync * Maybe more than one.

**Comment by wtrocki** [comment]
@camilamacedo86 Datasync is currently under development. It's not part of the release. Ping @darahayes @aliok @pb82 we should probably remove datasync as it will appear for community users.

**Comment by darahayes** [comment]
@camilamacedo86 Thanks very much for raising this. This was a mistake on our part. We accidentally published the Sync Service to the aerogearcatalog organisation a little too early. It should not be used yet.

Looping in @maleck13 to ask a question - Can we publish the sync apb (or any apb) to the aerogearcatalog docker org without it showing up in the community release version of the catalog?

**Comment by maleck13** [comment]
It shouldn't show up if there is no tag for 1.0.0 @camilamacedo86 when doing the install did you set the tag to latest?

**Comment by camilamacedo86** [comment]
@maleck13 to install it I follow the docs and I clone the project and I am using the tag 1.0.0.

**Comment by wtrocki** [comment]
@camilamacedo86 Tag is being set in the ASB (it's one of the questions on installer)

**Comment by wtrocki** [comment]
Yeah. Mobile-core repository tag is different than tag is being used to fetch apb's from dockerhub repository. 3th option in installer questions.

**Comment by camilamacedo86** [comment]
@wtrocki it is not good and it is not documented. The user should not need to do git clone, git checkout and answer in some of the many questions the tag version. Also, it is not documented, however, regards the installer I opened another issue https://github.com/aerogear/mobile-core/issues/129, then feel free to close this one if it is not a real bug.
