### ISSUE TITLE
Installer does not update oc version correctly

### ISSUE THREAD

**Issue by rachael-oregan** [aerogear/mobile-core#16]
## Description
The install script does not update the openshift-cli correctly.  It should update/install version 3.7.0 but instead it installs 3.6.0.

## Environment
*Operating system*: MacOS Sierra 

## Steps to reproduce
Remove your oc binary and run the install script
After installer has stopped check the oc version. It will be 3.6.0

**Comment by aidenkeating** [comment]
@rachael-oregan I can't seem to reproduce, have you checked that your roles are up to date?

**Comment by rachael-oregan** [comment]
@aidenkeating closing this issue as we confirmed this was a problem with ansible picking up the local version instead of the global

**Comment by aidenkeating** [comment]
@rachael-oregan https://github.com/aerogear/mobile-core/issues/22 Created from this discovery
