### ISSUE TITLE
Unable to bind the service Identify Management to cordova app when it is binding already to a android app

### ISSUE THREAD

**Issue by camilamacedo86** [aerogear/mobile-core#160]
## Description

**WHAT**: Unable to bind the service Identify Management to cordova app when it is binding already to a android app
**WHERE**: MyProject >> Overview
**WHEN** try to bind the  Identify Management to a cordova app when it is already linked to a Android app. Following the issue. 

<img width="1227" alt="screen shot 2018-07-12 at 12 33 12" src="https://user-images.githubusercontent.com/7708031/42630792-ff1f45b6-85cf-11e8-8332-80dc1e03ef2a.png">

Following the images shown how it is working with the Android app. 

<img width="1214" alt="screen shot 2018-07-12 at 12 33 31" src="https://user-images.githubusercontent.com/7708031/42630757-dd1ac9ae-85cf-11e8-9ffe-783ca6f0b8f3.png">

<img width="1195" alt="screen shot 2018-07-12 at 12 33 24" src="https://user-images.githubusercontent.com/7708031/42630768-e5629768-85cf-11e8-9664-cd834e4cee0d.png">

## Environment

*Operating system*: iOS
*OpenShift versions*: 3.9

## Steps to reproduce
1. Create an android app
2. Create an cordova app
3. Create an  Identify Management
4. Go to the MyProject >> Overview 
5. Bind the  Identify Management to the Android app
6. Try to bind it to de Cordova app.

**Comment by wei-lee** [comment]
Hi @camilamacedo86,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
