### ISSUE TITLE
Unable to check the errors and troubleshooting issues

### ISSUE THREAD

**Issue by camilamacedo86** [aerogear/mobile-core#161]
## Description
**WHAT**Unable to check the errors and troubleshooting issues
**WHERE** Projects/Services created via Mobile
**WHEN** something fails

Following an example, where a project was created and an app for it and a service which fails. 
<img width="1235" alt="screen shot 2018-07-12 at 14 05 28" src="https://user-images.githubusercontent.com/7708031/42634976-a8bc79de-85dc-11e8-836d-a7cf7e8432e9.png">

#### Expected behaviour:

It is expected to see the pods/services and get its logs when going inside of the project. However, it doesn't occur. 

```
cmacedo@camilas-MBP ~/mobile-core ((HEAD detached at 1.0.0)) $ oc project mobile
Already on project "mobile" on server "https://192.168.1.9:8443".
cmacedo@camilas-MBP ~/mobile-core ((HEAD detached at 1.0.0)) $ oc get all
No resources found.
```

After the provision finish, if it finish with success is possible check. However, it is not possible check what is going on when it fails. 

```
cmacedo@camilas-MBP ~/mobile-core ((HEAD detached at 1.0.0)) $ oc get all
NAME                                   REVISION   DESIRED   CURRENT   TRIGGERED BY
deploymentconfigs/data-sync-ui         1          1         1         config
deploymentconfigs/postgres-data-sync   1          1         1         config

NAME                  HOST/PORT                                PATH      SERVICES       PORT      TERMINATION     WILDCARD
routes/data-sync-ui   data-sync-ui-mobile.192.168.1.9.nip.io             data-sync-ui   web       edge/Redirect   None

NAME                            READY     STATUS    RESTARTS   AGE
po/data-sync-ui-1-deploy        1/1       Running   0          11s
po/data-sync-ui-1-tlpv9         1/2       Running   0          10s
po/postgres-data-sync-1-xc5xv   1/1       Running   0          24s

NAME                      DESIRED   CURRENT   READY     AGE
rc/data-sync-ui-1         1         1         0         11s
rc/postgres-data-sync-1   1         1         1         25s

NAME                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
svc/data-sync-ui         ClusterIP   172.30.109.213   <none>        443/TCP    10s
svc/postgres-data-sync   ClusterIP   172.30.61.202    <none>        5432/TCP   24s
cmacedo@camilas-MBP ~/mobile-core ((HEAD detached at 1.0.0)) $ 

```

## Environment

*Operating system*: iOS
*OpenShift versions*: 3.9

## Steps to reproduce
1. Create a project
2. Create an app for this project
3. Create a service for this project
4. Go to the command line and `oc project <new-project>` and `oc get all`. Nothing appears. How to debug and troubleshooting? 

To see it, for example, create a Connect Service and add invalid info. The provision of it will fail, how to check it?

**Comment by wei-lee** [comment]
Hi @camilamacedo86,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
