### ISSUE TITLE
Client application should be a hello world template with the SDK and config already made

### ISSUE THREAD

**Issue by camilamacedo86** [aerogear/mobile-core#162]
## Description

When a user creates a client app, is expected to have something actually to use. I think that a hello world template should be added at this point with the SDK already set up into it as the config created. Also, a link for the SDK docs as an explanation about how and where this setup/config should be added in client app view. 

<img width="1042" alt="screen shot 2018-07-12 at 13 07 53" src="https://user-images.githubusercontent.com/7708031/42632298-9c03337a-85d4-11e8-8178-8eb945e96501.png">

## Environment

*Operating system*: iOS
*OpenShift versions*: 3.9

## Steps to reproduce
- Create a client app
- Go to the project >> overview >> click on the client app

**Comment by wei-lee** [comment]
@camilamacedo86 

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
