### ISSUE TITLE
Bad usability to perform builds 

### ISSUE THREAD

**Issue by camilamacedo86** [aerogear/mobile-core#163]
## Description

**WHAT**: Bad usability to perform builds 
**WHERE** Project >> Overview >> Client app >> Build Tab
**WHEN**: Click on the build tab the following appears

<img width="997" alt="screen shot 2018-07-12 at 13 15 23" src="https://user-images.githubusercontent.com/7708031/42632616-ad04b9ea-85d5-11e8-9187-108425c57ac7.png">

#### Expected behaviour:
* It should be more intuitive and directly
* It is redirecting the user to Mobile Services when it could already show the correct option
* It could be set up a CI/CD Mobile Services instead of redirect to the Services in the catalogue

## Environment

*Operating system*: iOS
*OpenShift versions*: 3.9

**Comment by wei-lee** [comment]
Hi @camilamacedo86,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
