### ISSUE TITLE
Mobile CI|CD can be used for all platforms then why is required to add Android info? What means Android SDK package config in this point?

### ISSUE THREAD

**Issue by camilamacedo86** [aerogear/mobile-core#164]
## Description

Mobile CI|CD can be used for all platform then why is required to add Android info? What means Android SDK package config?

## Environment

*Operating system*: iOS
*OpenShift versions*: 3.9

## Steps to reproduce
Catalog >> Services >> Mobile CI|CD

**Comment by wei-lee** [comment]
Hi @camilamacedo86,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
