### ISSUE TITLE
If the cluster goes down is required performed the installation again

### ISSUE THREAD

**Issue by camilamacedo86** [aerogear/mobile-core#167]
## Description

If the cluster goes down is required performed the installation again, when, is expected that do it just once. 
## Environment

*Operating system*:iOS
*OpenShift versions*: 3.9

## Steps to reproduce
* Install the Mobile
* Check if it is working then shut down the OCP OR when an issue is faced and the OCP cluster die
* Start the OCP again the Mobile will be not so long there in the Catalog Browser

**Comment by wei-lee** [comment]
Hi @camilamacedo86,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
