### ISSUE TITLE
CI/DC why not have a toggle rather that a text box for yes

### ISSUE THREAD

**Issue by austincunningham** [aerogear/mobile-core#168]
## Description
More a feature request than issue
Why not have a radio button or toggle for the first field ?

![image](https://user-images.githubusercontent.com/16667688/42634436-23f9c7fc-85db-11e8-8e69-b63db8cb0bc4.png)

**Comment by camilamacedo86** [comment]
Duplicated of : https://github.com/aerogear/mobile-core/issues/152

**Comment by wei-lee** [comment]
Hi @austincunningham,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
