### ISSUE TITLE
Can't download cordova app apk from artifact-proxy-route URL

### ISSUE THREAD

**Issue by grdryn** [aerogear/mobile-core#169]
## Description
Link (https://artifact-proxy-route-myproject.10.201.82.56.nip.io/cordova-grdryn-pr98-2/download?token=cordova-grdryn-pr98-2-1531399784418&amp;artifact=true)

gives the following output rather than an apk to download:

<details>
invalid build type found for build &Build{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:cordova-grdryn-pr98-2,GenerateName:,Namespace:myproject,SelfLink:/apis/build.openshift.io/v1/namespaces/myproject/builds/cordova-grdryn-pr98-2,UID:0d0b20a6-85d2-11e8-acbd-54ee75775bc5,ResourceVersion:31113,Generation:0,CreationTimestamp:2018-07-12 12:49:44 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{buildconfig: cordova-grdryn-pr98,mobile-client-build: true,mobile-client-build-platform: android,mobile-client-id: my-cordova-app-cordova,mobile-client-type: cordova,openshift.io/build-config.name: cordova-grdryn-pr98,openshift.io/build.start-policy: Serial,},Annotations:map[string]string{aerogear.org/download-mobile-artifact: true,aerogear.org/download-mobile-artifact-url: https://artifact-proxy-route-myproject.10.201.82.56.nip.io/cordova-grdryn-pr98-2/download?token=cordova-grdryn-pr98-2-1531399784418&amp;artifact=true,aerogear.org/jenkins-mobile-artifact-url: https://jenkins-myproject.10.201.82.56.nip.io/job/myproject/job/myproject-cordova-grdryn-pr98/2/artifact/platforms/android/app/build/outputs/apk/debug/app-debug.apk,aerogear.org/mobile-artifact-token: cordova-grdryn-pr98-2-1531399784418,openshift.io/build-config.name: cordova-grdryn-pr98,openshift.io/build.number: 2,openshift.io/jenkins-blueocean-log-url: https://jenkins-myproject.10.201.82.56.nip.io/blue/organizations/jenkins/myproject%2Fmyproject-cordova-grdryn-pr98/detail/myproject-cordova-grdryn-pr98/2/,openshift.io/jenkins-build-uri: https://jenkins-myproject.10.201.82.56.nip.io/job/myproject/job/myproject-cordova-grdryn-pr98/2/,openshift.io/jenkins-console-log-url: https://jenkins-myproject.10.201.82.56.nip.io/job/myproject/job/myproject-cordova-grdryn-pr98/2/console,openshift.io/jenkins-log-url: https://jenkins-myproject.10.201.82.56.nip.io/job/myproject/job/myproject-cordova-grdryn-pr98/2/consoleText,openshift.io/jenkins-status-json: {"_links":{"self":{"href":"https://jenkins-myproject.10.201.82.56.nip.io/job/myproject/job/myproject-cordova-grdryn-pr98/2/wfapi/describe"},"changesets":{"href":"//job/myproject/job/myproject-cordova-grdryn-pr98/2/wfapi/changesets"},"pendingInputActions":null,"nextPendingInputAction":null,"artifacts":{"href":"//job/myproject/job/myproject-cordova-grdryn-pr98/2/wfapi/artifacts"}},"id":"2","name":"#2","status":"SUCCESS","startTimeMillis":1531399784424,"endTimeMillis":1531399784424,"durationMillis":0,"queueDurationMillis":6,"pauseDurationMillis":0,"stages":[{"_links":{"self":{"href":"https://jenkins-myproject.10.201.82.56.nip.io/job/myproject/job/myproject-cordova-grdryn-pr98/2/execution/node/7/wfapi/describe"},"log":null},"id":"7","name":"Checkout","execNode":"","status":"SUCCESS","error":null,"parameterDescription":null,"startTimeMillis":1531399788351,"durationMillis":10677,"pauseDurationMillis":0,"stageFlowNodes":[{"_links":{"self":{"href":"https://jenkins-myproject.10.201.82.56.nip.io/job/myproject/job/myproject-cordova-grdryn-pr98/2/execution/node/8/wfapi/describe"},"log":null},"id":"8","name":"General SCM","execNode":"","status":"SUCCESS","error":null,"parameterDescription":null,"startTimeMillis":1531399788394,"durationMillis":10614,"pauseDurationMillis":0,"parentNodes":["7"]}],"allChildNodeIds":["8"]},{"_links":{"self":{"href":"https://jenkins-myproject.10.201.82.56.nip.io/job/myproject/job/myproject-cordova-grdryn-pr98/2/execution/node/12/wfapi/describe"},"log":null},"id":"12","name":"Prepare","execNode":"","status":"SUCCESS","error":null,"parameterDescription":null,"startTimeMillis":1531399799087,"durationMillis":324786,"pauseDurationMillis":0,"stageFlowNodes":[{"_links":{"self":{"href":"https://jenkins-myproject.10.201.82.56.nip.io/job/myproject/job/myproject-cordova-grdryn-pr98/2/execution/node/13/wfapi/describe"},"log":null},"id":"13","name":"Shell Script","execNode":"","status":"SUCCESS","error":null,"parameterDescription":"npm i","startTimeMillis":1531399799154,"durationMillis":47153,"pauseDurationMillis":0,"parentNodes":["12"]},{"_links":{"self":{"href":"https://jenkins-myproject.10.201.82.56.nip.io/job/myproject/job/myproject-cordova-grdryn-pr98/2/execution/node/14/wfapi/describe"},"log":null},"id":"14","name":"Shell Script","execNode":"","status":"SUCCESS","error":null,"parameterDescription":null,"startTimeMillis":1531399846307,"durationMillis":5347,"pauseDurationMillis":0,"parentNodes":["13"]},{"_links":{"self":{"href":"https://jenkins-myproject.10.201.82.56.nip.io/job/myproject/job/myproject-cordova-grdryn-pr98/2/execution/node/15/wfapi/describe"},"log":null},"id":"15","name":"Shell Script","execNode":"","status":"SUCCESS","error":null,"parameterDescription":null,"startTimeMillis":1531399851654,"durationMillis":254604,"pauseDurationMillis":0,"parentNodes":["14"]},{"_links":{"self":{"href":"https://jenkins-myproject.10.201.82.56.nip.io/job/myproject/job/myproject-cordova-grdryn-pr98/2/execution/node/16/wfapi/describe"},"log":null},"id":"16","name":"Shell Script","execNode":"","status":"SUCCESS","error":null,"parameterDescription":null,"startTimeMillis":1531400106258,"durationMillis":17589,"pauseDurationMillis":0,"parentNodes":["15"]}],"allChildNodeIds":["13","14","15","16"]},{"_links":{"self":{"href":"https://jenkins-myproject.10.201.82.56.nip.io/job/myproject/job/myproject-cordova-grdryn-pr98/2/execution/node/20/wfapi/describe"},"log":null},"id":"20","name":"Build","execNode":"","status":"SUCCESS","error":null,"parameterDescription":null,"startTimeMillis":1531400123929,"durationMillis":46777,"pauseDurationMillis":0,"stageFlowNodes":[{"_links":{"self":{"href":"https://jenkins-myproject.10.201.82.56.nip.io/job/myproject/job/myproject-cordova-grdryn-pr98/2/execution/node/21/wfapi/describe"},"log":null},"id":"21","name":"Shell Script","execNode":"","status":"SUCCESS","error":null,"parameterDescription":null,"startTimeMillis":1531400123996,"durationMillis":46690,"pauseDurationMillis":0,"parentNodes":["20"]}],"allChildNodeIds":["21"]},{"_links":{"self":{"href":"https://jenkins-myproject.10.201.82.56.nip.io/job/myproject/job/myproject-cordova-grdryn-pr98/2/execution/node/25/wfapi/describe"},"log":null},"id":"25","name":"Sign","execNode":"","status":"SUCCESS","error":null,"parameterDescription":null,"startTimeMillis":1531400170773,"durationMillis":68,"pauseDurationMillis":0,"stageFlowNodes":[{"_links":{"self":{"href":"https://jenkins-myproject.10.201.82.56.nip.io/job/myproject/job/myproject-cordova-grdryn-pr98/2/execution/node/26/wfapi/describe"},"log":null},"id":"26","name":"Print Message","execNode":"","status":"SUCCESS","error":null,"parameterDescription":"Debug Build - Using default developer signing key","startTimeMillis":1531400170815,"durationMillis":6,"pauseDurationMillis":0,"parentNodes":["25"]}],"allChildNodeIds":["26"]},{"_links":{"self":{"href":"https://jenkins-myproject.10.201.82.56.nip.io/job/myproject/job/myproject-cordova-grdryn-pr98/2/execution/node/30/wfapi/describe"},"log":null},"id":"30","name":"Archive","execNode":"","status":"SUCCESS","error":null,"parameterDescription":null,"startTimeMillis":1531400170913,"durationMillis":2186,"pauseDurationMillis":0,"stageFlowNodes":[{"_links":{"self":{"href":"https://jenkins-myproject.10.201.82.56.nip.io/job/myproject/job/myproject-cordova-grdryn-pr98/2/execution/node/31/wfapi/describe"},"log":null},"id":"31","name":"General Build Step","execNode":"","status":"SUCCESS","error":null,"parameterDescription":null,"startTimeMillis":1531400170959,"durationMillis":2023,"pauseDurationMillis":0,"parentNodes":["30"]}],"allChildNodeIds":["31"]}]},},OwnerReferences:[{build.openshift.io/v1 BuildConfig cordova-grdryn-pr98 58ccb74a-85d0-11e8-acbd-54ee75775bc5 0xc420224168 <nil>}],Finalizers:[],ClusterName:,Initializers:nil,},Spec:BuildSpec{CommonSpec:CommonSpec{ServiceAccount:builder,Source:BuildSource{Type:Git,Binary:nil,Dockerfile:nil,Git:&GitBuildSource{URI:https://github.com/grdryn/cordova-showcase-template,Ref:fix-jenkinsfile,ProxyConfig:ProxyConfig{HTTPProxy:nil,HTTPSProxy:nil,NoProxy:nil,},},Images:[],ContextDir:,SourceSecret:nil,Secrets:[],},Revision:nil,Strategy:BuildStrategy{Type:JenkinsPipeline,DockerStrategy:nil,SourceStrategy:nil,CustomStrategy:nil,JenkinsPipelineStrategy:&JenkinsPipelineBuildStrategy{JenkinsfilePath:Jenkinsfile,Jenkinsfile:,Env:[{BUILD_CONFIG debug nil} {PLATFORM android nil}],},},Output:BuildOutput{To:nil,PushSecret:nil,ImageLabels:[],},Resources:k8s_io_api_core_v1.ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},},PostCommit:BuildPostCommitSpec{Command:[],Args:[],Script:,},CompletionDeadlineSeconds:nil,NodeSelector:map[],},TriggeredBy:[{Manually triggered nil nil nil nil nil}],},Status:BuildStatus{Phase:Complete,Cancelled:false,Reason:,Message:,StartTimestamp:2018-07-12 12:49:44 +0000 UTC,CompletionTimestamp:2018-07-12 12:56:13 +0000 UTC,Duration:0s,OutputDockerImageReference:,Config:&k8s_io_api_core_v1.ObjectReference{Kind:BuildConfig,Namespace:myproject,Name:cordova-grdryn-pr98,UID:,APIVersion:,ResourceVersion:,FieldPath:,},Output:BuildStatusOutput{To:nil,},Stages:[],LogSnippet:,},}
</details>

**Comment by PhilipGough** [comment]
Hey @grdryn . Would you mind pasting in the annotations that exist on this build please?

**Comment by maleck13** [comment]
issue created to track https://issues.jboss.org/browse/AEROGEAR-7566

**Comment by grdryn** [comment]
@PhilipGough unfortunately I didn't keep that cluster up. I might still be able to bring up the same one again, I'll try later or tomorrow if I get a chance.

**Comment by wei-lee** [comment]
HI @grdryn,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
