### ISSUE TITLE
KeyCloak Bindings won't create 

### ISSUE THREAD

**Issue by secondsun** [aerogear/mobile-core#17]
## Description
When I try to make a keycloak binding, it fails.  The error I got from the pod is : fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'admin_username' is undefined\n\nThe error appears to have been in '/opt/ansible/roles/bind-keycloak-apb/tasks/main.yml': line 16, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Generate keycloak auth token\"\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'admin_username' is undefined"}
	to retry, use: --limit @/opt/apb/actions/bind.retry

## Environment
*Operating system*:
Fedora 27
*OpenShift versions*: 
3.7.0
## Steps to reproduce
1. Create a KeyCloak service from the mobile tab using the default values
1. Create fh-sync-service using the default values 
1. Use Create Binding from the KeyCloak tab with the default bindings.

**Comment by maleck13** [comment]
@secondsun this is due to the params we pass to the bind playbook. We passed them from the server (this was before OpenShift supported bind params) now that they support bind params we should probably expose them as part of the APB pinging @wei-lee as they are looking at the kc apb

**Comment by aidenkeating** [comment]
@secondsun This should have been resolved. We have included a bind parameter to accept a service name. This should be visible in the OpenShift UI also when creating a binding.
