### ISSUE TITLE
SEC_ERROR_REUSED_ISSUER_AND_SERIAL Secure Connection Failed

### ISSUE THREAD

**Issue by davidkirwan** [aerogear/mobile-core#170]
## Description
Firefox displaying SEC_ERROR_REUSED_ISSUER_AND_SERIAL error when attempting to connect to the openshift console.

## Environment

*Operating system*: _Fedora release 28 (Twenty Eight)_
*OpenShift versions*: 
```
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
```

## Steps to reproduce

While following the instructions at: https://docs.aerogear.org/aerogear/latest/getting-started.html#prerequisites
- oc cluster up
- git clone https://github.com/aerogear/mobile-core.git
- cd mobile-core
- git checkout 1.0.0
- ./installer/install.sh
- opened https://10.32.240.178:8443/console/ in Firefox 61.0

![screenshot from 2018-07-12 14-48-55](https://user-images.githubusercontent.com/1700165/42637332-cb1112a0-85e2-11e8-85ab-1f16a0e7c7fc.png)

**Comment by wei-lee** [comment]
HI @davidkirwan,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
