### ISSUE TITLE
Installer fails when wildcard DNS suffix is specified as a blank string, ie ''

### ISSUE THREAD

**Issue by damienomurchu** [aerogear/mobile-core#173]
## Description

Installer assumes user is going to specify a suffix, or accept the nip.io default. If the user specifies a blank string as the suffix it causes the installer to fall over. 

Code lines in question: 
- https://github.com/aerogear/mobile-core/blob/1.0.0/installer/install.sh#L206
- https://github.com/aerogear/mobile-core/blob/c64ecf972b67596dcc9103c1a9cc47b183fc0d6b/installer/roles/oc-cluster-up/tasks/main.yml#L4 

## Environment

*Operating system*: fedora 26
*OpenShift versions*: 3.9

## Steps to reproduce

- run the install.sh script
- when prompted to enter a value for the Wildcard DNS Host, enter `''` as the value (ie `Wildcard DNS Host (Defaults to nip.io): ''`)
- watch oc cluster up fail. No log output to hand (sorry!)

**Comment by camilamacedo86** [comment]
@damienomurchu could you add the steps to specify a blank string '' for the Wildcard DNS Host ?

**Comment by damienomurchu** [comment]
Added additional detail above now

**Comment by camilamacedo86** [comment]
@damienomurchu Could you add the point where the installation fails and the error? Also, could you try do `oc cluster up` in this installation and see if it works?

**Comment by camilamacedo86** [comment]
@damienomurchu  the PR https://github.com/aerogear/mobile-core/pull/179 will solve this issue.

**Comment by maleck13** [comment]
fixed via https://github.com/aerogear/mobile-core/pull/179
