### ISSUE TITLE
Installer should not contain eng docs and demos

### ISSUE THREAD

**Issue by camilamacedo86** [aerogear/mobile-core#178]
## Description
The installer should not contain docs and demos, the installer should have what is relevant to it and is part of the process to install. When users do the download this process should be fast and light and they are not looking for videos, and images, and docs as for example Mobile Core Onboarding which is there etc .. ( doc directory ). It is not relevant to the users. 

#### Some suggestions:

* Create a doc repo for mobile-core eng and/or create a new repo just for the installer
* Publish the installer by some tool where just the executable files will be published/released

PS.: I found this discussion <https://groups.google.com/forum/#!topic/aerogear/1GDGeRQq6gk>, maybe it is the reason. 
## Environment

*Operating system*:
*OpenShift versions*: 

## Steps to reproduce
- Check the repo of the project

**Comment by camilamacedo86** [comment]
@maleck13 and @david-martin how we can solve it? Could we create a new repo just for the installer?

**Comment by wtrocki** [comment]
FYI @finp

**Comment by finp** [comment]
@camilamacedo86  some of this work is already underway as part of https://issues.jboss.org/browse/AEROGEAR-7611

**Comment by camilamacedo86** [comment]
@finp @wtrocki IHMO the installer should not contain any doc because the user will looking for it in the website. When a user downloads the installer the goal is just to install. However, shows required have the docs here in this repo according to the discussion in < https://groups.google.com/forum/#!topic/aerogear/1GDGeRQq6gk,>, then my suggestion is we have a repo just with the installer.

**Comment by finp** [comment]
@camilamacedo86  I don't think I should recommend removing all docs from mobile-core, neither do I think that the community decided to do that. I think the docs in this directory have some value and should be posted somewhere, what do you think of the following idea:
* docs get written in mobile-core
* when stable, those docs get posted as blog posts  
* docs get edited and moved to mobile-docs (removed from mobile-core)
The reason I suggest this, is that the style of the docs changes for docs.aerogear.org (eg fewer screenshots), and, to some, this might lessen their impact and having them as blog posts gives them a place which is timestamped so they dont' require updating

**Comment by wei-lee** [comment]
Hi @camilamacedo86,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
