### ISSUE TITLE
./installer/install.sh fails on linux

### ISSUE THREAD

**Issue by jstaffor** [aerogear/mobile-core#194]
## Description
./installer/install.sh fails

## Environment
Checking Docker version. 18.06.0-ce

Checking Python version. Python 2.7.5

Checking Ansible version. ansible 2.7.0

Checking OpenShift client tools version. oc v3.9.0

*Operating system*:
Linux jstaffor.remote.csb 3.10.0-693.21.1.el7.x86_64 #1 SMP Fri Feb 23 18:54:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

*OpenShift versions*: 
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

## Stack trace

TASK [oc-cluster-up : Cluster up] **********************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "oc cluster up --service-catalog=true --host-data-dir=/home/jstaffor/mext/mobile-core/ui/openshift-data --routing-suffix=192.168.3.178.nip.io --public-hostname=192.168.3.178 --version=v3.9.0 --image=openshift/origin", "delta": "0:11:00.208502", "end": "2018-07-25 10:12:24.762537", "msg": "non-zero return code", "rc": 1, "start": "2018-07-25 10:01:24.554035", "stderr": "FAIL\n   Error: failed to start the template service broker apiserver: timed out waiting for the condition", "stderr_lines": ["FAIL", "   Error: failed to start the template service broker apiserver: timed out waiting for the condition"], "stdout": "WARNING: Binding DNS on port 8053 instead of 53, which may not be resolvable from all clients.\nUsing nsenter mounter for OpenShift volumes\nUsing public hostname IP 192.168.3.178 as the host IP\nUsing 192.168.3.178 as the server IP\nStarting OpenShift using openshift/origin:v3.9.0 ...\n-- Starting OpenShift container ... \n   Creating initial OpenShift configuration\n   Starting OpenShift using container 'origin'\n   Waiting for API server to start listening\n   OpenShift server started\n-- Adding default OAuthClient redirect URIs ... OK\n-- Installing registry ... \n   scc \"privileged\" added to: [\"system:serviceaccount:default:registry\"]\n-- Installing router ... OK\n-- Importing image streams ... OK\n-- Importing templates ... OK\n-- Importing internal templates ... OK\n-- Installing service catalog ... OK\n-- Installing template service broker ... ", "stdout_lines": ["WARNING: Binding DNS on port 8053 instead of 53, which may not be resolvable from all clients.", "Using nsenter mounter for OpenShift volumes", "Using public hostname IP 192.168.3.178 as the host IP", "Using 192.168.3.178 as the server IP", "Starting OpenShift using openshift/origin:v3.9.0 ...", "-- Starting OpenShift container ... ", "   Creating initial OpenShift configuration", "   Starting OpenShift using container 'origin'", "   Waiting for API server to start listening", "   OpenShift server started", "-- Adding default OAuthClient redirect URIs ... OK", "-- Installing registry ... ", "   scc \"privileged\" added to: [\"system:serviceaccount:default:registry\"]", "-- Installing router ... OK", "-- Importing image streams ... OK", "-- Importing templates ... OK", "-- Importing internal templates ... OK", "-- Installing service catalog ... OK", "-- Installing template service broker ... "]}
	to retry, use: --limit @/home/jstaffor/mext/mobile-core/installer/playbook.retry
**********************************************

## `oc cluster up` command runs on my machine

[jstaffor@jstaffor ~]$ oc cluster up
WARNING: Binding DNS on port 8053 instead of 53, which may not be resolvable from all clients.
Using nsenter mounter for OpenShift volumes
Using 127.0.0.1 as the server IP
Starting OpenShift using openshift/origin:v3.9.0 ...
OpenShift server started.
The server is accessible via web console at:
    https://127.0.0.1:8443
You are logged in as:
    User:     developer
    Password: <any value>
To login as administrator:
    oc login -u system:admin

## Steps to reproduce

Create a setup based on the details above and run the installer: "./installer/install.sh"

**Comment by camilamacedo86** [comment]
Hi @jstaffor,

Could you check if the PR https://github.com/aerogear/mobile-core/pull/193 solve your issue? I believe that with it you will not face problems.

**Comment by jstaffor** [comment]
Hi @camilamacedo86 ,

I implemented PR #193 locally but unfortunately, the same error occurs.

John

**Comment by camilamacedo86** [comment]
Hi @jstaffor,

Thank you for let us know. After looking it further it shows some related to https://github.com/openshift/origin/issues/18747 and/or Note: https://github.com/openshift/ansible-service-broker/issues/585. 

`WARNING: Binding DNS on port 8053 instead of 53`
`Error: failed to start the template service broker apiserver: timed out waiting for the condition`

Regards the info provided you added `Linux jstaffor.remote.csb 3.10.0-693.21.1.el7.x86_64`, could you confirm that it is an RHEL/CentOS 7.4?

**Comment by jstaffor** [comment]
Hi @camilamacedo86, that's very interesting! 

I'm running "Red Hat Enterprise Linux Workstation 7.4" ... me thinks it is time to update to 7.5 :)

**Comment by jstaffor** [comment]
@pmacko1 - re "I would drop any mentions of rhel in docs.aerogear.org. Because it can give impression that RHEL is supported and I don't think we want to go that way." as mentioned in https://github.com/aerogear/mobile-docs/pull/301 - I have asked if we should reduce the prereqs in `docs.aerogear.org` from "MacOS or Linux"  to "MacOS or Fedora". See the following email thread for more info:

From: <jstaffor@redhat.com>
Date: Mon, Jul 30, 2018 at 1:49 PM
Subject: Re: Support RHEL as an OS to use with Mobile Services?
To: Aerogear <aerogear@googlegroups.com>

**Comment by camilamacedo86** [comment]
Hi @jstaffor  since we could confirm that it is an issue with OCP and RHEL 7.4 which is already tracked in its respective repos could we close this one?

**Comment by jstaffor** [comment]
Hi @camilamacedo86 - if I close this, it makes sense to reduce the scope of the prereqs to  "MacOS or Fedora" as Mobile Services does not run on RHEL due to https://github.com/openshift/origin/issues/18747 - do you agree?

**Comment by camilamacedo86** [comment]
@jstaffor I don't mean what do you mean with "reduce the scope of the prereqs to "MacOS or Fedora"? The issue is with RHEL/CentOS 7.4 and RHEL/CentOS 7.5 specifically and the problem is not in the installer/mobile. It is tracked here https://github.com/openshift/origin/issues/18747.

Then, IMHO the only action that we can take so far is to add in the mobile docs some not regards known issues. Is it make sense?

**Comment by jstaffor** [comment]
That is a much better suggestion IMO @camilamacedo86 :+1: 

I've added the following content to the upstream docs:

> NOTE: Due to an link:https://github.com/openshift/origin/issues/18747[OpenShift bug], {product-name} will not run on RHEL/CentOS 7.4 or RHEL/CentOS 7.5.
     
If you are happy with this, I'll commit https://github.com/aerogear/mobile-docs/pull/301/files and I'll be more than happy to close this issue :)

**Comment by jstaffor** [comment]
@camilamacedo86 - thanks for the assistance with this - it was much appreciated!

**Comment by camilamacedo86** [comment]
I am glad in to be helpful 👍
