### ISSUE TITLE
remove hard links to docs

### ISSUE THREAD

**Issue by finp** [aerogear/mobile-core#197]
## Description
hard links to docs

After installation, following is displayed:

INFO: For information on how to enable TLS communication on your device to this cluster see https://docs.aerogear.org/aerogear/latest/getting-started.html#using-self-signed-certificates-in-mobile-apps 

To avoid this linking, we can:

1. Create a redirect page in docs.aerogear.org repo.
2. Change installer/playbook.yml and installer/install.sh to use this redirect url

**Comment by finp** [comment]
addressed in #203

**Comment by pmacko1** [comment]
k to close then?
