### ISSUE TITLE
Unable to run oc cluster up on OS 3.10 - fails on flags passed

### ISSUE THREAD

**Issue by laurafitzgerald** [aerogear/mobile-core#202]
## Description
Trying to run the mobile-core installer but installer is failing on oc cluster up step.
Downgrading to oc 3.9 works but the [documentation](https://docs.aerogear.org/aerogear/latest/getting-started.html#prerequisites) states 3.9 or higher.

## Error
```
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "oc cluster up --service-catalog=true --host-data-dir=~/Aerogear/mobile-core/ui/openshift-data --routing-suffix=10.32.240.254.nip.io --public-hostname=10.32.240.254 --version=v3.9.0 --image=openshift/origin", "delta": "0:00:00.118130", "end": "2018-08-08 10:11:12.223845", "msg": "non-zero return code", "rc": 1, "start": "2018-08-08 10:11:12.105715", "stderr": **"Error: unknown flag: --service-catalog**
```

## Environment

*Operating system*:
MacOS High Sierra
Version 10.13.6

*OpenShift versions*: 
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8

## Steps to reproduce
Install oc client tools 3.10
Run `./installer/install.sh`

cc @philbrookes

**Comment by odra** [comment]
The new oc cli (3.10) uses a different cli arg to enable the service catalog component:

```oc cluster up --enable=service-catalog```

**Comment by laurafitzgerald** [comment]
@odra so this would require a change to the ansible commands to run one or the other based on version right?

**Comment by odra** [comment]
Yep, it will need to change the command arg if oc version is >= 3.10

**Comment by odra** [comment]
Looks like there is a better solution.

Just run the following command if >= 3.10:

```oc cluster add service-catalog```

**Comment by camilamacedo86** [comment]
@laurafitzgerald I believe that the text in the docs upper than 3.9 means 3.9.X but not 3.10. However, shows that we could make this work in the 3.10 easily

**Comment by wei-lee** [comment]
Hi @laurafitzgerald,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
