### ISSUE TITLE
Installer does not see oc client tools installed in /usr/local/bin when run as sudo

### ISSUE THREAD

**Issue by pmacko1** [aerogear/mobile-core#207]
```
Checking OpenShift client tools exists
? OpenShift Client tools do not exist on host. They will be installed by the MCP installer.
Where do you want to install oc?:  (/usr/local/bin)
```
- Fedora 28
- master branch of mobile-core
```
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
```

**Comment by pmacko1** [comment]
@camilamacedo86 could you ping someone re this? thanks!

**Comment by camilamacedo86** [comment]
Hi @pmacko1 ,

This message just occurs if the oc is not installed. The check is made [here|https://github.com/aerogear/mobile-core/blob/master/installer/install.sh#L248]. See that to check it the command oc will be called. 

It is important to highlight that Linux SO allows you to install and give specific permissions for each user. I don't see it as a problem. 

If this happened, then execute the command `oc version` with the same user used to execute the script. It will be a bug if you execute it and the command is found the script should find it too and if the command is not found then the script will try to install it. Could you check?

**Comment by pmacko1** [comment]
yeah, this resolves this, thank you for your time and effort @camilamacedo86 !
