### ISSUE TITLE
Installer fails when trying to use it on debian stretch

### ISSUE THREAD

**Issue by droidscout** [aerogear/mobile-core#212]
## Description
If I execute the installer script on debian stretch (9.6) the installer fails on task "andrewrothstein.unarchive-deps : install common pkgs..."

## Expected Behavior
 TASK [output-oc-cluster-status : debug] ******************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "Web console URL: https://192.168.37.1:8443/console/",
        "",
        "Config is at host directory /var/lib/origin/openshift.local.config",
        "Volumes are at host directory /var/lib/origin/openshift.local.volumes",
        "Persistent volumes are at host directory /var/lib/origin/openshift.local.pv",
        "Data is at host directory /path/to/mobile-core/ui/openshift-data"
    ]
}

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=44   changed=17   unreachable=0    failed=0

## Actual Behavior
TASK [andrewrothstein.unarchive-deps : install common pkgs...]***************************************
failed: [localhost] (item=unzip) => {"changed": false, "item": "unzip", "msg": "Could not import python modules: apt, apt_pkg. Please install python3-apt package." }
failed: [localhost] (item=gzip) => {"changed": false, "item": "gzip", "msg": "Could not import python modules: apt, apt_pkg. Please install python3-apt package." }
failed: [localhost] (item=bzip2) => {"changed": false, "item": "bzip2", "msg": "Could not import python modules: apt, apt_pkg. Please install python3-apt package." }
failed: [localhost] (item=tar) => {"changed": false, "item": "tar", "msg": "Could not import python modules: apt, apt_pkg. Please install python3-apt package." }
failed: [localhost] (item=xz-utils) => {"changed": false, "item": "xz-utils", "msg": "Could not import python modules: apt, apt_pkg. Please install python3-apt package." }

## Environment

* Operating system: Debian Stretch 9.6 in virtualbox environment
* OpenShift versions: v3.11.0+0cbc58b
* Project Versions: commit 674be67d6d81760b4d20301350e3d694ba00c036

## Steps to reproduce
Install Python 3.7 from source. Although it might not work with python3.7, I've installed "python3-apt" with aptitude. 
Follow the "getting started guide: https://docs.aerogear.org/aerogear/latest/getting-started.html#setting-up-your-local-development-environment"

Thank you in advance.

Regards,
Ralph

**Comment by wei-lee** [comment]
Hi @droidscout,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.
