### ISSUE TITLE
Missing installer roles

### ISSUE THREAD

**Issue by evanshortiss** [aerogear/mobile-core#57]
## Description
When running the installer via `./installer/install.sh` the following error is raised:

```
ERROR! the role 'install-socat' was not found in /Users/eshortis/workspaces/rhmap/mobile-core/installer/roles:/Users/eshortis/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/Users/eshortis/workspaces/rhmap/mobile-core/installer

The error appears to have been in '/Users/eshortis/workspaces/rhmap/mobile-core/installer/playbook.yml': line 6, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
  - role: install-socat
    ^ here
```

This can be fixed by commenting it from the `playbook.yml`, but then this happens:

```
ERROR! the role 'openshift-origin-client-tools' was not found in /Users/eshortis/workspaces/rhmap/mobile-core/installer/roles:/Users/eshortis/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/Users/eshortis/workspaces/rhmap/mobile-core/installer

The error appears to have been in '/Users/eshortis/workspaces/rhmap/mobile-core/installer/playbook.yml': line 9, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


  - role: openshift-origin-client-tools
    ^ here
```

Similarly, it can be fixed by commenting out if the tools exists on your machine already.

## Environment
* ansible - 2.4.2.0
* oc - v3.7.1+ab0f056

*Operating system*: macOS - 10.12.6

## Steps to reproduce
Per above, run `installer/install.sh`

**Comment by maleck13** [comment]
@evanshortiss thanks for the issue. In the meantime, could you try using the minishift plugin that we have available?
https://github.com/aerogear/minishift-mobilecore-addon

@philbrookes @aidenkeating  any thoughts on this one?

**Comment by aidenkeating** [comment]
@evanshortiss Do you have the full output of running `./installer/install.sh` available? It looks like the Ansible Galaxy roles aren't being included in `./installer/roles/` correctly but I cannot reproduce the issue.

**Comment by evanshortiss** [comment]
Updating to Ansible 2.5+ fixed this. It seems to be some issue related to the OpenSSL version used by Python on macOS (brew version vs system installed version)

Anyways. Fixed!
